# This CI will only work for project members. CI for public contributors
# runs via a webhook on the merge requests. There's nothing you have to do if
# you want your changes tested -- created pipeline will be automatically
# linked in the merge request and appropriate labels will be added to it.
# Changes to this file will NOT be reflected in the webhook testing.

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE =~ /^(merge_request_event|web|api|trigger|schedule)$/'

trigger_pipeline:
  variables:
    git_url: ${CI_MERGE_REQUEST_SOURCE_PROJECT_URL}
    branch: ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
    commit_hash: ${CI_COMMIT_SHA}
    name: kernel-ark-${CI_MERGE_REQUEST_ID}
    child_pipeline: 'True'
    target_repo: $CI_MERGE_REQUEST_PROJECT_URL
    target_branch: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    mr_id: ${CI_MERGE_REQUEST_ID}
    title: ${CI_COMMIT_TITLE}

    kernel_type: upstream
    make_target: rpm
    builder_image: registry.gitlab.com/cki-project/containers/builder-rawhide
    builder_image_tag: latest
    srpm_make_target: dist-srpm
    arch_override: 'x86_64 ppc64le aarch64 s390x'
    tree_name: upstream
    package_name: kernel
    # We only need srpm so skip the rest of the stages
    skip_build: 'true'
    skip_publish: 'true'
    skip_test: 'true'
  trigger:
    project: cki-runs/trusted-pipelines
    branch: kernel-ark
    strategy: depend


merge_upstream:
  variables:
    GIT_DEPTH: "0"
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/kernel-ark
  before_script:
    - echo "fastestmirror=true" >> /etc/dnf/dnf.conf
    - dnf -y install python3-gitlab git openssh-clients dnf-utils gnupg2
    - git config user.name "Fedora Kernel Team"
    - git config user.email "kernel-team@fedoraproject.org"
    - echo "$PYTHON_GITLAB_CONFIG" >> ~/.python-gitlab.cfg
    # Need SSH since the clone is set up without write access.
    - eval $(ssh-agent -s)
    - echo "$PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$GITLAB_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - git remote add gitlab git@gitlab.com:cki-project/kernel-ark.git
    - gpg2 --import "$TORVALDS_GPG_KEY"
  script:
    - git checkout --track origin/master && git describe
    - git checkout --track origin/os-build && git describe
    - export PROJECT_ID="$CI_PROJECT_ID"
    - make dist-merge-upstream || exit 1
  retry: 2
  only:
    refs:
      - schedules
    variables:
      - $RAWHIDE_RELEASE == "dummy"
